train_path = '.\\data\\DailyDelhiClimateTrain.csv'
test_path = '.\\data\\DailyDelhiClimateTest.csv'
view_path = '.\\data\\DailyDelhiClimateView.csv'
model_path = '.\\model\\linear_model.pkl'
scaler_path = '.\\model\\scaler.pkl'
image_path = '.\\image\\Animation.gif'
